### ISSUE TITLE
can you add the function that export to csv file?

### ISSUE THREAD

**Issue by bincker** [flight-tom/NewOSql#1]
can you add the function that export to csv file?

now the log file is not regular query result.

**Comment by flight-tom** [comment]
**Dear @bincker ,**

Through your mention, I just realized the log function exactly not work.
I will fix the log function in days.

**About your proposal**
I will add export function with new arguments to support.

TODO
================

- [x] Fix log function.
- [x] Support export feature and format indecation.

Thanks

**Comment by flight-tom** [comment]
Functionality has been done, but needs code refining from messy.
